apiVersion: v1
kind: Service
metadata:
  name: redis-instance-service
spec:
  selector:
    app: redis-instance
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
  type: LoadBalancer
