apiVersion: v1
kind: Service
metadata:
  name: redis-instance-service
spec:
  selector:
    app: redis-instance
  ports:
    - protocol: TCP
      port: 6379         # Port exposed to the outside world
      targetPort: 6379   # The Redis pod's internal port
      nodePort: 30007    # Port to be used on the node (must be between 30000-32767)
  type: NodePort         # Use NodePort for local testing
